/**
 * Cargo Audit Scanner Tests
 * 
 * Tests that the cargo-audit scanner correctly detects and classifies
 * Rust dependency vulnerabilities at the expected severity levels.
 */

import { scanCargoDependencies } from '../../scanners/cargo-audit';
import { writeFileSync, mkdirSync, unlinkSync, existsSync } from 'fs';
import { join } from 'path';

describe('Cargo Audit Scanner', () => {
  const testFixtureDir = join(__dirname, 'fixtures', 'cargo-audit');

  beforeEach(() => {
    mkdirSync(testFixtureDir, { recursive: true });
  });

  afterEach(() => {
    if (existsSync(join(testFixtureDir, 'Cargo.lock'))) {
      unlinkSync(join(testFixtureDir, 'Cargo.lock'));
    }
  });

  test('detects vulnerable Rust dependencies and classifies severity correctly', () => {
    // Create a Cargo.lock with a vulnerable dependency structure
    const cargoLock = `
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "test-project"
version = "0.1.0"

[[package]]
name = "vulnerable-crate"
version = "0.1.0"
`;

    writeFileSync(join(testFixtureDir, 'Cargo.lock'), cargoLock);

    // Run the scanner
    const vulnerabilities = scanCargoDependencies(testFixtureDir);

    // Verify structure
    expect(Array.isArray(vulnerabilities)).toBe(true);
    
    if (vulnerabilities.length > 0) {
      const vuln = vulnerabilities[0];
      expect(vuln).toHaveProperty('id');
      expect(vuln).toHaveProperty('source');
      expect(vuln).toHaveProperty('severity');
      expect(vuln).toHaveProperty('title');
      expect(vuln).toHaveProperty('description');
      expect(vuln).toHaveProperty('location');
      expect(vuln).toHaveProperty('metadata');
      expect(vuln).toHaveProperty('remediation');
      
      expect(vuln.source).toBe('dependency');
      expect(vuln.location).toHaveProperty('package');
      expect(vuln.location).toHaveProperty('version');
      
      expect(['critical', 'high', 'medium', 'low', 'info']).toContain(vuln.severity);
    }
  });

  test('handles missing Cargo.lock gracefully', () => {
    // No Cargo.lock file
    const vulnerabilities = scanCargoDependencies(testFixtureDir);
    expect(vulnerabilities).toEqual([]);
  });

  test('normalizes cargo audit severity based on CVSS score', () => {
    const cargoLock = `
version = 3

[[package]]
name = "test-project"
version = "0.1.0"
`;

    writeFileSync(join(testFixtureDir, 'Cargo.lock'), cargoLock);

    const vulnerabilities = scanCargoDependencies(testFixtureDir);
    
    for (const vuln of vulnerabilities) {
      expect(['critical', 'high', 'medium', 'low', 'info']).toContain(vuln.severity);
    }
  });

  test('extracts RUSTSEC and CVE identifiers', () => {
    const cargoLock = `
version = 3

[[package]]
name = "test-project"
version = "0.1.0"
`;

    writeFileSync(join(testFixtureDir, 'Cargo.lock'), cargoLock);

    const vulnerabilities = scanCargoDependencies(testFixtureDir);
    
    for (const vuln of vulnerabilities) {
      expect(vuln).toHaveProperty('metadata');
      expect(vuln.metadata).toHaveProperty('cve');
      expect(vuln.metadata).toHaveProperty('cvss');
      expect(vuln.metadata).toHaveProperty('references');
      
      // CVE should be in format CVE-YYYY-NNNN if present
      if (vuln.metadata.cve) {
        expect(vuln.metadata.cve).toMatch(/^CVE-\d{4}-\d+$/);
      }
    }
  });
});
